trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AWSCreds

jobs:
- job: deploy_infrastructure
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DownloadSecureFile@1
    name: aws_credentials
    displayName: 'Download AWS Credentials'
    inputs:
      secureFile: 'aws-credentials.json'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform apply -auto-approve \
        -var "aws_access_key=$(AWS_ACCESS_KEY)" \
        -var "aws_secret_key=$(AWS_SECRET_KEY)"
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
