trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: AWS_ACCESS_KEY
    value: $(access-key)
  - name: AWS_SECRET_KEY
    value: $(secret-key)

jobs:
- job: deploy_infrastructure
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform apply -auto-approve \
        -var "AWS_ACCESS_KEY=$(access-key)" \
        -var "AWS_SECRET_KEY=$(secret-key)"
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
