trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: aws_access_key_id
    value: $(access-key)
  - name: aws_secret_access_key
    value: $(secret-key)

jobs:
- job: deploy_infrastructure
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - script: |
      aws configure set aws_access_key_id $(access-key)
      aws configure set aws_secret_access_key $(secret-key)
    displayName: 'Configure AWS CLI'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      cd $(Build.SourcesDirectory)/_aws-ec2-terraform-AzureDevops
      terraform apply -auto-approve \
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
